# Generated by Django 4.2.7 on 2023-12-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commos', '0002_notas_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=30)),
                ('parrafo', models.TextField()),
                ('noticia_larga', models.TextField()),
                ('imagen', models.ImageField(upload_to='noticias/')),
            ],
        ),
        migrations.DeleteModel(
            name='Notas',
        ),
    ]
