# Generated by Django 4.2.7 on 2023-12-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commos', '0003_noticia_delete_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.FileField(upload_to='noticas/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.TextField(),
        ),
    ]
