# Generated by Django 4.2.7 on 2023-12-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commos', '0006_alter_noticia_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='noticia_larga',
            new_name='noticial',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='id',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='usuario',
        ),
        migrations.AddField(
            model_name='noticia',
            name='codigo',
            field=models.CharField(default='0', max_length=6, primary_key=True, serialize=False),
        ),
    ]
