# Generated by Django 4.2.7 on 2023-12-07 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commos', '0007_rename_noticia_larga_noticia_noticial_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticia',
            new_name='Noti',
        ),
    ]
