# Generated by Django 4.2.7 on 2023-12-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commos', '0008_rename_noticia_noti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('titulo', models.TextField()),
                ('parrafo', models.TextField()),
                ('noticia_larga', models.TextField()),
                ('imagen', models.FileField(upload_to='noticas/')),
            ],
        ),
        migrations.DeleteModel(
            name='Noti',
        ),
    ]
