# Generated by Django 4.2.7 on 2023-12-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commos', '0009_noticia_delete_noti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noti',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('parrafo', models.TextField()),
                ('noticial', models.TextField()),
                ('imagen', models.FileField(upload_to='noticas/')),
            ],
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
