# Generated by Django 4.2.7 on 2023-12-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commos', '0010_noti_delete_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noti',
            name='categoria',
            field=models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Vans', 'Vans'), ('Otros', 'Otros')], default='Otros', max_length=10),
        ),
    ]
